export const debugMode = false,
  maxEntitiesToMatch = Infinity,
  maxRelatedEntities = Infinity,
  openaiApiKey = "your api key goes here",
  openaiModel = "gpt-3.5-turbo-1106",
  openaiMaxTokens = 16_000,
  huggingfaceEntityModel = "dslim/bert-base-NER",
  huggingfaceRelationModel = "Babelscape/rebel-large",
  huggingfaceApiKey = "your api key goes here";
