// only useful for testing on this page:
// https://theintercept.com/2024/01/13/penn-palestine-writes-liz-magill/
export const interceptExtractionData = {
  entities: [
    {
      id: 0,
      name: "Liz Magill",
      type: "person",
    },
    {
      id: 1,
      name: "Stefanik",
      type: "person",
    },
    {
      id: 2,
      name: "Scott Bok",
      type: "person",
    },
    {
      id: 3,
      name: "Susan Abulhawa",
      type: "person",
    },
    {
      id: 4,
      name: "Jewish Federation of Greater Philadelphia",
      type: "organization",
    },
    {
      id: 5,
      name: "Anti-Defamation League of Philadelphia",
      type: "organization",
    },
    {
      id: 6,
      name: "University of Pennsylvania",
      type: "organization",
    },
    {
      id: 7,
      name: "Penn",
      type: "organization",
    },
    {
      id: 8,
      name: "J. Larry Jameson",
      type: "person",
    },
    {
      id: 9,
      name: "Bill Mullen",
      type: "person",
    },
    {
      id: 10,
      name: "Julie Platt",
      type: "person",
    },
    {
      id: 11,
      name: "Jewish Federations of North America",
      type: "organization",
    },
    {
      id: 12,
      name: "Josh Shapiro",
      type: "person",
    },
    {
      id: 13,
      name: "Art Council",
      type: "organization",
    },
    {
      id: 14,
      name: "Marie Kelly",
      type: "person",
    },
  ],
  relationships: [
    {
      entity1_id: 0,
      entity2_id: 2,
      description: "resigned together",
    },
    {
      entity1_id: 0,
      entity2_id: 6,
      description: "University of Pennsylvania",
    },
    {
      entity1_id: 0,
      entity2_id: 7,
      description: "University of Pennsylvania",
    },
    {
      entity1_id: 0,
      entity2_id: 1,
      description: "Stefanik’s line of questioning",
    },
    {
      entity1_id: 0,
      entity2_id: 9,
      description: "board member of Palestine Writes",
    },
    {
      entity1_id: 0,
      entity2_id: 10,
      description: "vice chair of the university board",
    },
    {
      entity1_id: 4,
      entity2_id: 0,
      description: "sent letters to Magill",
    },
    {
      entity1_id: 5,
      entity2_id: 0,
      description: "sent letters to Magill",
    },
    {
      entity1_id: 6,
      entity2_id: 3,
      description: "citing concerns about certain speakers",
    },
    {
      entity1_id: 6,
      entity2_id: 13,
      description: "represented in court proceedings",
    },
    {
      entity1_id: 6,
      entity2_id: 14,
      description: "board member for Palestine Writes",
    },
    {
      entity1_id: 11,
      entity2_id: 10,
      description: "Platt also serves as board chair",
    },
    {
      entity1_id: 12,
      entity2_id: 13,
      description: "represented the arts council in court proceedings",
    },
  ],
};

// only useful for testing on this page:
// https://www.latimes.com/politics/story/2024-01-07/kamala-harris-doug-emhoff-los-angeles-home-brentwood
export const laTimesEntities = [
  {
    id: 0,
    name: "Air Force Two",
    type: "organization",
    related: ["Kamala Harris"],
  },
  { id: 1, name: "LAX", type: "organization" },
  {
    id: 2,
    name: "Kamala Harris",
    type: "person",
    related: [
      "Doug Emhoff",
      "Joe Biden",
      "The Times",
      "Laphonza Butler",
      "Brian Brokaw",
      "Chrisette Hudlin",
      "Brentwood",
      "Air Force Two",
      "The Naval Observatory",
      "Melanie Apple Fields",
      "King Abdullah II of Jordan",
    ],
  },
  {
    id: 3,
    name: "Doug Emhoff",
    type: "person",
    related: [
      "Kamala Harris",
      "Cole Emhoff",
      "Ella Emhoff",
      "The Times",
      "Chrisette Hudlin",
      "Brentwood",
      "The Naval Observatory",
    ],
  },
  {
    id: 4,
    name: "Cole Emhoff",
    type: "person",
    related: ["Doug Emhoff", "Greenley Littlejohn"],
  },
  {
    id: 5,
    name: "Greenley Littlejohn",
    type: "person",
    related: ["Cole Emhoff"],
  },
  { id: 6, name: "El Cholo", type: "organization" },
  {
    id: 7,
    name: "The Times",
    type: "organization",
    related: ["Doug Emhoff", "Kamala Harris"],
  },
  { id: 8, name: "Joe Biden", type: "person", related: ["Kamala Harris"] },
  {
    id: 9,
    name: "Brentwood",
    type: "organization",
    related: ["Kamala Harris", "Doug Emhoff", "Getty fire"],
  },
  {
    id: 10,
    name: "The Naval Observatory",
    type: "organization",
    related: ["Kamala Harris", "Doug Emhoff"],
  },
  {
    id: 11,
    name: "Laphonza Butler",
    type: "person",
    related: ["Kamala Harris"],
  },
  { id: 12, name: "Ella Emhoff", type: "person", related: ["Doug Emhoff"] },
  { id: 13, name: "Brian Brokaw", type: "person", related: ["Kamala Harris"] },
  {
    id: 14,
    name: "Chrisette Hudlin",
    type: "person",
    related: ["Kamala Harris", "Doug Emhoff"],
  },
  { id: 15, name: "Hollywood Bowl", type: "organization" },
  { id: 16, name: "Cinerama Dome", type: "organization" },
  { id: 17, name: "Huntington Meats", type: "organization" },
  { id: 18, name: "Gearys", type: "organization" },
  { id: 19, name: "Zankou Chicken", type: "organization" },
  { id: 20, name: "Guelaguetza", type: "organization" },
  { id: 21, name: "Toscana", type: "organization" },
  { id: 22, name: "Craig's", type: "organization" },
  { id: 23, name: "Hillcrest", type: "organization" },
  { id: 24, name: "Frida's", type: "organization" },
  { id: 25, name: "Zero 7", type: "organization" },
  { id: 26, name: "Golden State Warriors", type: "organization" },
  { id: 27, name: "Lakers", type: "organization" },
  { id: 28, name: "Getty fire", type: "organization", related: ["Brentwood"] },
  {
    id: 29,
    name: "Melanie Apple Fields",
    type: "person",
    related: ["Voyage et Cie", "Kamala Harris", "Jill Biden"],
  },
  {
    id: 30,
    name: "Voyage et Cie",
    type: "organization",
    related: ["Melanie Apple Fields", "Alex Padilla"],
  },
  { id: 31, name: "Studio City", type: "organization" },
  { id: 32, name: "Alex Padilla", type: "person", related: ["Voyage et Cie"] },
  {
    id: 33,
    name: "King Abdullah II of Jordan",
    type: "person",
    related: ["Kamala Harris"],
  },
  { id: 34, name: "Nina Ricci", type: "organization" },
  { id: 35, name: "Peninsula", type: "organization" },
  {
    id: 36,
    name: "Jill Biden",
    type: "person",
    related: ["Melanie Apple Fields"],
  },
  {
    id: 37,
    name: "Courtney Subramanian",
    type: "person",
    related: ["Los Angeles Times"],
  },
  {
    id: 38,
    name: "Los Angeles Times",
    type: "organization",
    related: ["Courtney Subramanian", "Christina House"],
  },
  {
    id: 39,
    name: "Christina House",
    type: "person",
    related: ["Los Angeles Times"],
  },
  { id: 40, name: "Cal State Fullerton", type: "organization" },
  { id: 41, name: "Robert F. Kennedy Journalism Award", type: "organization" },
];
